const sampleMenuData = [
    {
        "opKind": "",
        "menuId": "90000",
        "parentMenuId": "00000",
        "sts": "0",
        "upmuCode": "AA..",
        "menuName": "Sample",
        "srcUrl": ".",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "Sample",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90001",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA01",
        "menuName": "Report Call Sample",
        "srcUrl": "aa/AA01.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "Report Call Sample",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90002",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA02",
        "menuName": "Entry Screen Sample (LN10)",
        "srcUrl": "aa/AA02.html",
        "trType": "E1",
        "buttonFlag": "110000",
        "serviceName": "",
        "localName": "Entry Screen Sample (LN10)",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90003",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA03",
        "menuName": "Popup Screen Sample (CH0101)",
        "srcUrl": "aa/AA03.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "Popup Screen Sample (CH0101)",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90004",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA04",
        "menuName": "Popup Call Sample",
        "srcUrl": "aa/AA04.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "Popup Call Sample",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90005",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA05",
        "menuName": "Service Call Sample",
        "srcUrl": "aa/AA05.html",
        "trType": "E1",
        "buttonFlag": "110000",
        "serviceName": "",
        "localName": "Service Call Sample",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90006",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA06",
        "menuName": "File Management Sample",
        "srcUrl": "aa/AA06.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "File Management Sample",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90007",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA07",
        "menuName": "FTP Sample",
        "srcUrl": "aa/AA07.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "FTP Sample",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90008",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA08",
        "menuName": "File Upload & Download Sample (BD31)",
        "srcUrl": "aa/AA08.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "File Upload & Download Sample (BD31)",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90009",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA09",
        "menuName": "Excel Import & Export Sample",
        "srcUrl": "aa/AA09.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "Excel Import & Export Sample",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90010",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA10",
        "menuName": "ActiveXObject(Msxml2) Convert (RE64)",
        "srcUrl": "aa/AA10.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "ActiveXObject(Msxml2) Convert Sample (RE64)",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90011",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA11",
        "menuName": "ActiveXObject(Excel) Convert (CE21)",
        "srcUrl": "aa/AA11.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "ActiveXObject(Excel) Convert Sample (CE21)",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90012",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA12",
        "menuName": "ActiveXObject(FileSystemObject) Convert (XP11, commonCE)",
        "srcUrl": "aa/AA12.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "ActiveXObject(FileSystemObject) Convert Sample (XP11, commonCE)",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90013",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA13",
        "menuName": "Image Viewer",
        "srcUrl": "aa/AA13.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "Image Viewer",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90025",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA25",
        "menuName": "PassBook",
        "srcUrl": "aa/AA25.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "PassBook",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90026",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA26",
        "menuName": "Scanner",
        "srcUrl": "aa/AA26.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "Scanner",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90026",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA27",
        "menuName": "Scan Image View",
        "srcUrl": "aa/AA27.html",
        "trType": "I1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "Scan Image View",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    },
    {
        "opKind": "",
        "menuId": "90050",
        "parentMenuId": "90000",
        "sts": "0",
        "upmuCode": "AA50",
        "menuName": "Screen for Development Practice",
        "srcUrl": "aa/AA50.html",
        "trType": "E1",
        "buttonFlag": "000000",
        "serviceName": "",
        "localName": "Screen for Development Practice",
        "sortSeq": "0",
        "menuPath": "",
        "maUpmu": ""
    }
];